---
- name: Install Nginx
  apt:
    name: nginx
    state: present
 
- name: Generate Nginx site config
  template:
    src: site.conf.j2
    dest: /etc/nginx/sites-available/site.conf
    owner: root
    group: root
    mode: 0644

- name: Generate index.html
  copy:
    src: "{{ index_file }}"
    dest: /var/www/html/
    owner: root
    group: root
    mode: 0644

- name: Start Nginx
  command: /usr/sbin/nginx

